# Site settings
title: N1NF Mind
email: github@N1NFMind.com
description: > # this means to ignore newlines until "baseurl:"
  Going beyond "normal" database design
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://n1nfmind.com" # the base hostname & protocol for your site
github_username:  n1nfmind

# Build settings
markdown: kramdown

# Outputting
# permalink: none
